spring:
  redis:
    host: localhost
    database: 0 # Redis 数据库索引（默认为0）
    port: 6379
    password: # redis 服务器连接密码（默认为空）
    jedis:
      pool:
        max-active: 8 # 连接池最大连接数量 ( 使用负值表示没有限制）
        max-wait: -1ms # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 8 # 连接池中最大的空闲连接
        min-idle: 0 # 连接池中的最小空闲连接
    connect-timeout: 3000ms # 连接超时时间（毫秒）
