spring:
  datasource:
    url: jdbc:postgresql://localhost:54322/mydb001
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
server:
  port: 30001
