spring:
  datasource:
    url: jdbc:postgresql://192.168.232.128:5432/test
    username: postgres
    password: mzrfviwhninayh
    driver-class-name: org.postgresql.Driver

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
